# fly.toml app configuration file generated for despina on 2025-05-09T06:46:53Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'despina'
primary_region = 'sea'

[build]

[[services]]
  internal_port = 8081
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
